import type { Metadata } from "next";
import "./globals.css";
import {
  ClerkProvider,
  SignIn,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="antialiased bg-gray-900 text-white">
          <SignedIn>{children}</SignedIn>
          <SignedOut>
            <section className="min-h-screen flex items-center justify-center w-screen">
              <SignIn />
            </section>
          </SignedOut>
        </body>
      </html>
    </ClerkProvider>
  );
}
